version: '{build}'
os: Visual Studio 2017
environment:
  JAVA_OPTS: -Dfile.encoding=UTF8
  SBT_OPTS: -Dfile.encoding=UTF8
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4G -XX:MaxPermSize=1G
build_script:
  - sbt +compile
test_script:
  - sbt +test
