name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: sbt

      - name: Check formatting
        run: sbt javafmtCheckAll scalafmtCheckAll

  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 17, 21]
        scala: [3.3.3]
        include:
          - scala: 2.13.14
            os: ubuntu-latest
            java: 21
          - scala: 2.12.20
            os: ubuntu-latest
            java: 21

    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: sbt

      - name: Setup sbt
        if: startsWith(runner.os, 'macOS')
        run: |
          brew install sbt
          sbt sbtVersion

      - name: Build project
        run: sbt ++${{ matrix.scala }} test
        shell: bash
