name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.15

      - name: Check formatting
        run: sbt javafmtCheckAll scalafmtCheckAll

  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [adopt@1.8, zulu@1.17]
        scala: [2.12.10, 2.13.10, 3.2.2]
        exclude:
          - scala: 2.12.10
            os: macos-latest
          - scala: 2.12.10
            os: windows-latest
          - scala: 2.12.10
            java: adopt@1.8
          - scala: 2.13.10
            os: macos-latest
          - scala: 2.13.10
            os: windows-latest
          - scala: 2.13.10
            java: adopt@1.8

    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash

      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: Build project
        run: sbt ++${{ matrix.scala }} test
        shell: bash
